### ISSUE TITLE
lay out options for version-control and/or backups of database

### ISSUE THREAD

**Issue by nickreich** [reichlab/forecast-repository#134] opened 2019-04-17 00:05 UTC

**Comment by matthewcornell** [comment] 2019-04-18 12:21
https://devcenter.heroku.com/articles/heroku-postgres-backups

> Every professional tier Heroku Postgres database comes with a behind-the-scenes Continuous Protection mechanism for disaster recovery, as well as optional “logical” backups under your direct control.




https://devcenter.heroku.com/articles/heroku-postgres-data-safety-and-continuous-protection

**Comment by nickreich** [comment] 2019-04-18 13:02
I would like to discuss more the pros and cons of having a more detailed "versioned" system. Maybe not a full git style versioning of the database, but perhaps something kind of close to that.

**Comment by matthewcornell** [comment] 2019-04-18 13:09
Ahh - gotcha. well I'm glad I researched backups anyway.

**Comment by matthewcornell** [comment] 2019-04-18 13:15
My first thought is that it would be a massive rewrite, but I need to know the details of what you have in mind. Then again, we might be able to do something simpler than backing up every row in the database whenever there's a change, maybe something like keeping all forecast csv files around after uploading instead of deleting them.

**Comment by nickreich** [comment] 2019-04-18 13:24
I am perhaps more interested in keeping a versioned history of scores than forecasts themselves, but need to think a bit more about this before triggering any re-writes. let's discuss in person next time we meet.

**Comment by matthewcornell** [comment] 2020-11-18 13:56
@nickreich is this a duplicate of my just-closed #273 ?

**Closed** 2020-11-24 18:02 UTC
Labels: design
